package Model;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Model.Timer.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//


public class Timer {
    private Game game;

    private void tick() throws Exception {
        game.step();
    }

    public void start() throws Exception {
        tick();
    }
}
