name: CI on branch main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types:
    - opened
    - synchronize

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B package -DskipTests org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=BME-MIT-IET_iet-hf-2022-szamitosok --no-transfer-progress
    - name: Upload built jar
      uses: actions/upload-artifact@v3
      with:
        name: Built jar
        path: target/astronaut-game-1.0-SNAPSHOT.jar
        if-no-files-found: error
        retention-days: 1
